### ISSUE TITLE
cant start on kernel any chance can fix this?

### ISSUE THREAD

**Issue by xsmashx88x** [qwerasd205/BDPlugins#11]
[
![image](https://user-images.githubusercontent.com/16874197/172902790-f6940e58-0cc3-419b-a4aa-80e251afa443.png)
](url)

**Comment by qwerasd205** [comment]
This is a BD plugin, not a kernel plugin -- if it doesn't work on Kernel then that's a problem with Kernel's BD compat, not the plugin.
