### ISSUE TITLE
[QuickView] QuickView could not be started.

### ISSUE THREAD

**Issue by rollingmoai** [qwerasd205/BDPlugins#16]
Loading the plugin for the first time works. But when restarting, this happens:
![image](https://user-images.githubusercontent.com/75471378/199141012-e48a599a-763d-4834-8b36-d795db19a926.png)

**Comment by qwerasd205** [comment]
Cannot reproduce. I tested reloading and restarting the client and toggling the plugin off and on - no problems.

Please provide more details about when/how this error occurs. Additionally, provide details about what version of Discord you're running and what version of BD.

**Comment by rollingmoai** [comment]
- Discord PTB
- Betterdiscord 1.8.2

**Steps to Reproduce**
1. Load plugin for the first time
2. Plugin works
3. Restart Discord
4. Error appears and enabling it now fails.

![image](https://user-images.githubusercontent.com/75471378/199142729-8d472c3e-903f-44ea-be1b-64aecc93e36d.png)

**Comment by qwerasd205** [comment]
Does this issue still occur for you?

**Comment by rollingmoai** [comment]
It still occurs with the same error, unfortunately.
![image](https://user-images.githubusercontent.com/75471378/206345634-aba1207f-e4a7-49e5-8044-03284e66ea4d.png)

**Comment by rollingmoai** [comment]
I've tested QuickView in the stable channel, and the issue doesn't seem to appear there.
