### ISSUE TITLE
[AlwaysOnTop] Does absolutely nothing.

### ISSUE THREAD

**Issue by packmore** [qwerasd205/BDPlugins#26]
i've been having the same issue for a while now - one day, alwaysontop was working, the next, it's not. i assume an update broke it, because i made a clean wipe of both betterdiscord and my plugins folder and, while it had the "Always on top enabled/disabled" pop-up this time, it still made absolutely no difference. not to mention that the config can't be edited, either. it results in the same error every time.
![image](https://github.com/qwerasd205/BDPlugins/assets/159909786/0b43d12a-d00f-4f40-a292-13c024ba482d)

**Comment by qwerasd205** [comment]
Unfortunately, I no longer maintain these plugins, sorry. I should probably delist them.

**Comment by packmore** [comment]
> Unfortunately, I no longer maintain these plugins, sorry. I should probably delist them.

would probably help with frustation if they weren't even available to be frustrated at, i suppose. 
so, that would be for the best.
