### ISSUE TITLE
Pinned Icon should not appear in Pinned Messages area

### ISSUE THREAD

**Issue by radzo73** [qwerasd205/BDPlugins#3]
![image](https://user-images.githubusercontent.com/26673668/132429317-71a30f17-0bbd-4dc0-94a1-f66e85b7ab44.png)
Like I already know it's pinned, because, uh
it's in the pinned messages area

**Comment by qwerasd205** [comment]
Added in version 0.0.3, which you can download from betterdiscord.app whenever the update gets approved (shouldn't be too long, it's a very small code change)
