### ISSUE TITLE
PinIcon throwing unknown errors.

### ISSUE THREAD

**Issue by EvieUwU** [qwerasd205/BDPlugins#4]
Hi, PinIcon is throwing a lot of errors at the moment but I do not know what they are because of a bug in betterdiscord not logging the error thrown. Strencher has opened a pull request to fix this in betterdiscord, but you might be able to do something before thats accepted.
![image](https://user-images.githubusercontent.com/54776821/132738218-95d3afad-afa2-4f45-8489-3aa251b01bdb.png)
![image](https://user-images.githubusercontent.com/54776821/132738226-48ff070f-7654-45d9-a0c6-3cbb10a2b068.png)
The plugin itself does not work either.
![image](https://user-images.githubusercontent.com/54776821/132738474-569e1c3a-222a-45f9-b35b-d19fec7d9426.png)

**Comment by qwerasd205** [comment]
Cannot reproduce -- plugin working fine for me on Discord Stable.

**Comment by qwerasd205** [comment]
May be due to an interaction with another plugin, disable all other plugins and enable them one at a time until you find the one that causes the problem.

**Comment by EvelynProto** [comment]
I've disabled all my other plugins, except for zeres lib and the icon still does not load.
I don't have any themes installed either.

**Comment by qwerasd205** [comment]
This issue is very stale, I've fixed many errors in PinIcon since, so I'm closing this.
