### ISSUE TITLE
[AlwaysOnTop] Idea: Give an option to automatically disable when the program is maximized

### ISSUE THREAD

**Issue by noahstreller** [qwerasd205/BDPlugins#6]
Hi!

I like this plugin, it helps me a lot to multitask on my convertible notebook without having to open discord all the time.
I would love to see an option though, which toggles AlwaysOnTop automatically, when Discord is maximized; because as soon as i want to open another program, I have to toggle it manually to off (or the program will run "behind" Discord). 
It might also confuse people, if they forgot that AOT is active, and their apps don't show up when they start them. 

Summary: disable AOT when maximized and re-enable it when using it in a normal window.

Sorry for my bad english-

Greetings, 
Noah Streller

**Comment by qwerasd205** [comment]
This is an excellent idea, I'll see if it's possible to implement. Thank you for the feedback.

**Comment by qwerasd205** [comment]
I've just implemented this feature in version 1.2.0 -- it can be enabled in the plugin's settings. Thank you for the suggestion!
