### ISSUE TITLE
Error every launch for QuickView

### ISSUE THREAD

**Issue by ImDini** [qwerasd205/BDPlugins#9]
For a week or so now you are not able to use the QuickView plugin. Every time you launch discord it has an error saying "Quick View" which goes away when you remove the plugin. Also, the plugin isn't visible in the plugins tab so you have to open plugins folder to remove it.

**Comment by qwerasd205** [comment]
What version of the plugin do you have? Have you tried redownloading it?

**Comment by ImDini** [comment]
> What version of the plugin do you have? Have you tried redownloading it?

With the latest version on here it loads at least but it does not function. ALT+Click has no affect on anything
